export const FETCH_SELF_USER_DATA = 'FETCH_SELF_USER_DATA';
export const FETCH_ALL_CATEGORIES = 'FETCH_ALL_CATEGORIES';

// Map
export const SET_CURRENT_POSITION = 'SET_CURRENT_POSITION';

export const ACTION = {
  FETCH_SELF_USER_DATA,
  FETCH_ALL_CATEGORIES,
  SET_CURRENT_POSITION,
};
