export const FETCH_SELF_USER_DATA = 'FETCH_SELF_USER_DATA';
export const FETCH_ALL_CATEGORIES = 'FETCH_ALL_CATEGORIES';
export const SET_CURRENT_LOCALE = 'SET_CURRENT_LOCALE';
export const UPDATE_CURRENT_LOCALE = 'UPDATE_CURRENT_LOCALE';

// Map
export const SET_CURRENT_POSITION = 'SET_CURRENT_POSITION';

// Search
export const SEARCH_VENUES = 'SEARCH_VENUES';
export const SEARCH_VENUE_BY_ID = 'SEARCH_VENUE_BY_ID';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_SEARCH_CATEGORY = 'SET_SEARCH_CATEGORY';
export const SET_SEARCH_VENUE_ID = 'SET_SEARCH_VENUE_ID';
export const FETCH_SPECIFIC_VENUE_DETAIL = 'FETCH_SPECIFIC_VENUE_DETAIL';

export const UPDATE_MAP_HEIGHT = 'UPDATE_MAP_HEIGHT';

export const PROPOSE_EDIT = 'PROPOSE_EDIT';

export const ACTION = {
  FETCH_SELF_USER_DATA,
  FETCH_ALL_CATEGORIES,
  SET_CURRENT_LOCALE,
  UPDATE_CURRENT_LOCALE,
  SET_CURRENT_POSITION,
  SEARCH_VENUES,
  SEARCH_VENUE_BY_ID,
  SET_SEARCH_QUERY,
  SET_SEARCH_CATEGORY,
  SET_SEARCH_VENUE_ID,
  FETCH_SPECIFIC_VENUE_DETAIL,
  UPDATE_MAP_HEIGHT,
  PROPOSE_EDIT,
};
