export const SET_SELF_USER_DATA = 'SET_SELF_USER_DATA';
export const SET_AVATAR_URL = 'SET_AVATAR_URL';
export const SET_CURRENT_LOCALE = 'SET_CURRENT_LOCALE';
export const UPDATE_CURRENT_LOCALE = 'UPDATE_CURRENT_LOCALE';
export const SET_ALL_CATEGORIES = 'SET_ALL_CATEGORIES';

// Search
export const SET_CURRENT_POSITION = 'SET_CURRENT_POSITION';
export const SET_SEARCHED_VENUES = 'SET_SEARCHED_VENUES';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_SEARCH_CATEGORY = 'SET_SEARCH_CATEGORY';
export const SET_SPECIFIC_VENUE_DETAIL = 'SET_SPECIFIC_VENUE_DETAIL';

export const SET_MAP_HEIGHT = 'SET_MAP_HEIGHT';

export const MUTATION = {
  SET_SELF_USER_DATA,
  SET_AVATAR_URL,
  SET_CURRENT_LOCALE,
  UPDATE_CURRENT_LOCALE,
  SET_ALL_CATEGORIES,
  SET_CURRENT_POSITION,
  SET_SEARCHED_VENUES,
  SET_SEARCH_QUERY,
  SET_SEARCH_CATEGORY,
  SET_SPECIFIC_VENUE_DETAIL,
  SET_MAP_HEIGHT,
};
