export const SET_SELF_USER_DATA = 'SET_SELF_USER_DATA';
export const SET_AVATAR_URL = 'SET_AVATAR_URL';
export const SET_ALL_CATEGORIES = 'SET_ALL_CATEGORIES';

export const MUTATION = {
  SET_SELF_USER_DATA,
  SET_AVATAR_URL,
  SET_ALL_CATEGORIES,
};
